### ISSUE TITLE
Render tagline, title and subtitle

### ISSUE THREAD

**Issue by tilsammans** [codevise/pageflow-linkmap-page#10]
It's clear to me why output of tagline, title and subtitle is not included in the linkmap page. These have fixed placement and this can interfere with the hotspots.

However we find ourselves wanting to include text to guide the visitor inside the page. It's not elegant to have to do this on a page before the hotspot page.

I propose this solution:

- [ ] render tagline, title and subtitle inside the page type
- [ ] default to `display: none`
- [ ] include the page ID in a wrapping div so the titles can be targeted using CSS
- [ ] allow theme developers to display and position the titles on a case by case basis

Thoughts?

**Comment by tilsammans** [comment]
A simpler alternative would be to introduce a toggle to show/hide the titles.

And let people just work around the fixed placement.

Including some unique id/class into the DOM would still be helpful for CSS fine-tuning however.

**Comment by tf** [comment]
I see your point, but I must admit I'm a bit scared of adding this additional complexity. The main problem that I see is that the linkmap page uses the page scroller to achieve its panorama effect. I therefore see two possibilities:

1. Place the titles inside the scroller and have them move out of viewport when scrolling
2. Place the titles outside the scroller to display them above the moving panorama

Option 1. has the downside that there is no easy way to constrain the size of the titles to fit into the viewport. Having to pan the panorama to read the whole title will sure seem broken,

With option 2. there is no way of handling overflowing titles on small viewports. Moreover, on older IEs, there is no `pointer-events`, so we would need to find a way to let the user interact with the panorama through the titles.

Finally, I'm quite opposed to the idea of leaving such difficult and brittle decisions to the theme author. We went through the work intensive process of migrating all our themes to use the configurable default theme and I'd regret having to move in another direction again. Otherwise we'll have no way of changing the linkmap page in the future without breaking custom themes again.

So if we find a way to make this happen, I'd open for it, but from my point of view the solution would have to live in the page types code base - even if it is disabled by default.

**Comment by tilsammans** [comment]
I propose I fork the page type first and work out the kinks in our productions. Afterwards we can apply the learnings upstream, or we can keep maintaining the forked version for ourselves.

**Comment by tf** [comment]
Ok. Let me know if you need any help/pointers.
