### ISSUE TITLE
Small typo Backgrund

### ISSUE THREAD

**Issue by tilsammans** [codevise/pageflow-linkmap-page#9]
I cannot edit [this translation](https://accounts.localeapp.com/projects/8781/translations/5103877?in_locale=26596) it seems. Backgrund needs to be Background.

**Comment by tf** [comment]
Really strange. In the LocaleApp user settings it says that you can edit all translations. Can you check again?

**Comment by tilsammans** [comment]
I can update `de` and `nl` on that page fine, but `en` not. It has a do-not-enter sign and no buttons appear. This is for all of English in the entire project, by the way.

**Comment by tf** [comment]
Strange. I'll open a support request with LocaleApp. Also I have applied the typo fix. Thanks for reporting. I'll leave this ticket open as a reminder, until we have a response form LocaleApp.

**Comment by tf** [comment]
Ok. So support answered that you need to be a developer to edit translations in the source locale. There should be a role in between translator and developer to allow this, from my point of view, but there obviously isn't at the moment.

Regarding, `nl` translations outside of `pageflow-public-i18n`. So far, our plan has been to only support English and German translations since those are easy for us to come up with when developing new features. If a Dutch version of the admin/editor is a priority for you, we could look into making sure `en` works as a fallback so Dutch translations could be updated/added step by step.

**Comment by tilsammans** [comment]
No, it's not a priority for me!
